#!/bin/sh

# Script for adding files to prevent startup wizard and tutorial
touch ~/.jolla-startupwizard-done
touch ~/.jolla-startupwizard-usersession-done
touch ~/.jolla-startupwizard-sfos2-tutorial
