#!/bin/sh

# Script for disabling ALS
dbus-send --system --type=method_call --print-reply --dest=com.nokia.mce /com/nokia/mce/request com.nokia.mce.request.set_config string:/system/osso/dsm/display/als_enabled variant:boolean:false
