#!/bin/sh

# Script for setting default ambience
# First find out what home version, and then change the command to point to a specific ambience config
if [ $(rpm -q lipstick-jolla-home-qt5 --queryformat "%{VERSION}" | awk -F. '{print $1}') -eq  0 ]
then
    if [ $(rpm -q lipstick-jolla-home-qt5 --queryformat "%{VERSION}" | awk -F. '{print $2}') -le 24 ]
    then
        echo "/usr/share/ambience/robo-ambience/robo-ambience.ambience" > /usr/share/jolla-preload/ambience/ambience-default.conf
    else
        echo "/usr/share/ambience/robo-ambience/robo-ambience-home2.ambience" > /usr/share/jolla-preload/ambience/ambience-default.conf
    fi
else
    echo "/usr/share/ambience/robo-ambience/robo-ambience-home2.ambience" > /usr/share/jolla-preload/ambience/ambience-default.conf
fi
